source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'bcrypt'
gem 'newrelic_rpm'
gem 'oj'

group :development do
  gem 'rack-lineprof'
  gem 'stackprof', git: 'git@github.com:osyoyu/stackprof.git'
  gem 'byebug'
  gem 'sinatra-contrib'
end
